services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/n8n-io/n8n
    plan: free
    region: oregon
    dockerfilePath: docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: thaintd
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123456
      - key: N8N_HOST
        value: n8n-thaind.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-thaintd.onrender.com
